# Generated by Django 4.1 on 2022-08-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("title", models.CharField(max_length=256)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("name", models.CharField(max_length=128, verbose_name="называния")),
                ("size", models.CharField(max_length=8, verbose_name="размер")),
                ("clen", models.SlugField(max_length=256, verbose_name="длина")),
                (
                    "nton",
                    models.CharField(max_length=256, verbose_name="норма в тоннах"),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("is_active", models.BooleanField(default=True)),
                ("is_discount", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "product",
            },
        ),
    ]
